name: Auto Commit

on:
  schedule:
    - cron: "0 * * * *" # Menjalankan workflow setiap jam

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate random file
        run: |
          date > random-file.txt
          echo "Automated commit on $(date)" >> random-file.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Automated commit"
          git push
